apiVersion: apps/v1
kind: Deployment
metadata:
  name: tika
  namespace: paperless
  labels: &labels
    app.kubernetes.io/component: paperless
    app.kubernetes.io/name: tika
spec:
  selector:
    matchLabels: *labels
  replicas: 1
  template:
    metadata:
      labels: *labels
    spec:
      containers:
      - name: tika
        image: abhilesh7/apache-tika-arm:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Gi
        ports:
        - containerPort: 9998
          name: gotenberg
      restartPolicy: Always
