apiVersion: v1
kind: Service
metadata:
  name: tika
  namespace: paperless
  labels: &labels
    app.kubernetes.io/component: paperless
    app.kubernetes.io/name: tika
spec:
  selector: *labels
  ports:
  - name: tika
    port: 9998
    targetPort: 9998
