apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb-helm-chart
  namespace: mariadb
spec:
  chart:
    spec:
      chart: mariadb
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 14.1.0
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: mariadb
  targetNamespace: mariadb
  upgrade:
    crds: CreateReplace
  values:
    volumePermissions:
      enabled: true
