apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-pv-consume
  namespace: paperless
  labels:
    app.kubernetes.io/name: paperless
    app.kubernetes.io/component: paperless-pv-consume
    type: local
spec:
  storageClassName: manual-consume
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/rookian/k8s-volumes/paperless/consume"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-consume-pvc
  namespace: paperless
  labels:
    app.kubernetes.io/name: paperless
    app.kubernetes.io/component: paperless-consume-pvc
spec:
  storageClassName: manual-consume
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

