apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-pv-data
  namespace: paperless
  labels:
    app.kubernetes.io/name: paperless
    app.kubernetes.io/component: paperless-pv-data
    type: local
spec:
  storageClassName: manual-data
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/rookian/k8s-volumes/paperless/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data-pvc
  namespace: paperless
  labels:
    app.kubernetes.io/name: paperless
    app.kubernetes.io/component: paperless-data-pvc
spec:
  storageClassName: manual-data
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

