resources:
  - namespace.yaml
  - secrets
  - gotenberg
  - tika
  - postgres
  - rclone
  - data-pvc.yaml
  - media-pvc.yaml
  - consume-pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
