apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-pv-media
  namespace: paperless
  labels:
    app.kubernetes.io/name: paperless
    app.kubernetes.io/component: paperless-pv-media
    type: local
spec:
  storageClassName: manual-media
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/rookian/k8s-volumes/paperless/media"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-media-pvc
  namespace: paperless
  labels:
    app.kubernetes.io/name: paperless
    app.kubernetes.io/component: paperless-media-pvc
spec:
  storageClassName: manual-media
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

