apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: paperless
  namespace: paperless
spec:
  encryptedData:
    secretKey: AgBw2XLyGIOnn3acLXx/cwb/k77jHJktr3kicgsjm8i5R6rDOt4i2O9y3c51IbTrZ3fWKdsE+Bj5hzeiubTCAYyTmStzhp5m/EmyDL4iVAmJATlhTCH82ofTONRzQnpS+rIscg/nxJnC6nZfN52ho2RRdx+3SNiNud2zXyKKoPJFtmQJ2hP8xEreOUpdqG8hPPGV/1m39bkcPmAVklgWTrNECUgp5Rs4WAGtyhEDAbQwM8Wl4ZgCuGKlfl17y5GQw0P7tBGVXS/6MzSlC647W3WLDgHU76jlVscUVB374W87L1ZfusD6ZMr3450CIGJlxGBITd2Sp1pBYLJzPH6aib1AZSiIUk/WWwbL9J0nTIbyBD8r8Oad22QgJzWmeGaILWFoJiaIpbx+zpcMs8/zXobsV700uxKHWUH9nxHvEdLOD5jeN2a7bzOMZ+9nCU1v98Goh8213H2SL7xVXDgzPmBxjyShXN4SG80ViZNW6fuFwAiwz303NIcW6qFtPi+DE92eSOW60MGknseADCOb52eIZ+oPzQyjp4+ijkpHuZ4FiQOcz8xTWSXIedWY820RAgV4jsFE7PBaTeIMZEIynXXMIb+D1fx08Kt3d/mSGc8Jl4plEt86g9yWh2NhTHXE7ZAnqw3EY3ymP7jlgCW6mXGg4gjnY+h18LdprbYW7nGgLWD4Z9YGD2Q1Va27MbMhSvQrA5WOmJfyphwXohoMsGf438O+GuPuEkCFuGIN41/0cLZTm4Hy
  template:
    metadata:
      creationTimestamp: null
      name: paperless
      namespace: paperless

