apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: paperless
  namespace: paperless
spec:
  encryptedData:
    secretKey: AgB0f+5nP7vOxwHlgIdRKqNUAkZ8ncHW9oXHr/x8x2Us68s78aqehm2uPfj9wtUHMbPnS1G6YjbV/7xQCPvFiO1cXKoISH77BfKh2bCuQpZT1fL7oRhZhAT6OW7ZWp1SefaDv7rudyQaVJ+m+z/FiBLLg9WjcSl+hfcxf6pgLKwL3Y3uf00QgsjFrsjnpB+MmgYBuGADkOl8LOc4lRRNjLwe/eW/cPIIYmwqRQOYPkzXoIz57tBhtnfs0bueviahBO/qOuvR+zP4CO/HSKYI5WQ/rd0FUuGxEGWtubCM6P+XeikP6cPsokKqTxLrpsLbr+ERgxABTGbBfS0QJkjhTVRTEVbwPO4Fhug1iptm6IB4LLC1Sy/n95Cq/SF13hvxN9LdchC/3smSMN+fQCJ8mdOjvvQ5x09lP4nRUIGV7P+UKmbUDkY9zcmjCoC5sJXf6AbfGRFSOyWnQ56GcYLZ9fyccWTSxEd3fYosJXbd+ffNXDMLpUcZ+wf4FpPEjFOZaq1bzB3lhORqhQkwA30pVrAgtffS4/nSfBuJ29J82V4p0QVdfGfjOpt/J2nbRFdRNp4evvEGQDGsEZFqMcjxx2/HudtZb75efVvd+20KGDWnypzIztas/1H/23evoyhqSiOogfiAttbd1EPsQ2kV4ANaXeJ/yV89boznHpw3sdcaJrJnAC/T7W+hDT0600wAm6ls0irJWZe7+SIk1nriJegxLIXb0AHmPvUtZMq1BRYCeNYtK/RW
  template:
    metadata:
      creationTimestamp: null
      name: paperless
      namespace: paperless

