---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data-pvc
  namespace: immich
  labels:
    app: mysql-ghost
    app.kubernetes.io/name: immich-data-pvc
    app.kubernetes.io/instance: immich
    app.kubernetes.io/component: data-storage
    app.kubernetes.io/part-of: immich
spec:
  storageClassName: hcloud-volumes
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
