---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  chart:
    spec:
      chart: immich
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: immich
      version: 0.7.1
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: immich
  targetNamespace: immich
  upgrade:
    crds: CreateReplace
  values:
    env:
      DB_DATABASE_NAME:
        valueFrom:
          secretKeyRef:
            name: postgres-password
            key: database
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: postgres-password
            key: username
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: postgres-password
            key: password
      DB_HOSTNAME: 10.0.0.3
    image:
      tag: v1.112.1
    immich:
      persistence:
        library:
          existingClaim: immich-data-pvc
    postgresql:
      global:
        postgresql:
          auth:
            existingSecret: postgres-password
    redis:
      enabled: true
    server:
      probes:
        liveness:
          spec:
            initialDelaySeconds: 120
        readiness:
          spec:
            initialDelaySeconds: 120
      ingress:
        main:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: lets-encrypt
          hosts:
            - host: photos.rookian.dev
              paths:
                - path: "/"
          tls:
            - hosts:
                - photos.rookian.dev
              secretName: tls-photos-rookian.dev
