apiVersion: batch/v1
kind: CronJob
metadata:
  name: import-files-from-onedrive
  namespace: paperless
spec:
  # every 5 minutes
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: import-from-onedrive
            image: rclone/rclone:latest
            args: ['move', 'OneDrive:Dokumente/Office\ Lens', '/tmp/paperless/consume']
            volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /tmp/paperless/consume
              name: paperless-consume
            - mountPath: /config/rclone
              name: rclone-config
          restartPolicy: OnFailure
          volumes:
          - name: data
            emptyDir: {}
          - name: rclone-config
            secret:
              secretName: rclone-config
          - name: paperless-consume
            persistentVolumeClaim:
              claimName: paperless-consume-pvc
