# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: gotenberg
  namespace: paperless
  labels: &labels
    app.kubernetes.io/component: paperless
    app.kubernetes.io/name: gotenberg
spec:
  selector: *labels
  ports:
  - name: gotenberg
    port: 3000
    targetPort: 3000
