apiVersion: v1
kind: Service
metadata:
  name: gotenberg
  namespace: paperless
  labels: &labels
    app.kubernetes.io/component: gotenberg
    app.kubernetes.io/name: paperless
spec:
  selector: *labels
  ports:
  - name: gotenberg
    port: 3000
    targetPort: 3000
