---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: flux-system
spec:
  chart:
    spec:
      chart: postgresql
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 12.8.2
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: postgres
  targetNamespace: paperless
  upgrade:
    crds: CreateReplace
  values:
    image:
      debug: true
    volumePermissions:
      enabled: true
    auth:
      username: paperless
      database: paperless
      existingSecret: postgres-secrets
