apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secrets
  namespace: paperless
spec:
  encryptedData:
    password: AgAN3OQEV8mDiTDrlTP5PqCu1BE+VfY6p4Ug17t/MDpqXZR4/15Cv4YL6Laan9iHQvKc/H0H2bggNTVr9To1xt9b93X+2Ahk959MVXXhhQEdCaAfwrde7pl+CCAxjAdWE67sIL4qTJLT9FsfOePo0sAiwXR1uIzlc4lSEx78F94VvCLSy0Ugo3Q1ESLogVFZ1z0gytKI8ZemXbiB3cAKikCXjlCDT+uLdlzVJpGsUZddGCkYQC34lqx5BGhk5QpaH3TlnY3sJ52meJCNPtWSv5aOpePFnO53syWEavxuDgGRKyMDmDfMeTkVkhLest4qnGRTtONaLGr2N7sq8tUV0OvYIxvSCRlI2zvcZyWEf7yKm4uZEcQr+D06rqBfu+5VbsYetm+iKd2+UoYcm4rpiBW8LsFNorH6beBMZelqn8sRRYWyNhYNNondj+gjIziiMtF4hsQKUdf2gWcxnXvIijoLIATnpwlv9b1rwel4v9srI1dP3qGtzbtsWtyjCsu6G2SZpUA249vBt2w7Pf4BxVfGW1JTQkcWVRZ7WDCkXQWNP0GcZRVXYyKWHtZvMpC4PgAWDsL0VBIvyuA+JsEDq7O3b6pEIXY78rfSfI+aVgzetoqzRBIqtESpiZ59SiRNC6/bLNdeGzEDdkQmqwPphWQPl1aGS8OOai2T28z97NskTtmAWu7+OXJE0YevweOlx4USuEUOaiiKSpBuBQWx9fjXdflrnyA1AkjPOmFC1L52+qV5VNxI6Jw6Qss+giHen7y5
    postgres-password: AgB6e4KR8BREctbDnGLfahqqK8Mm/vGwcX+dZ1/hRw7nylargZxgeWEQ3twYekygB2x4DIADwUDsZw1vnkRWfb6Zyr1cjYc2U9q8skH2maKW7+QWjtVbYwq9eZutsw6O7ZwNFEelD0DoVKTLYx0h7fTozTYjADcFRE0YRUMC2MOdsfo677mJy5hxcVWwjtkC2/YSssXMRjHtfZWZxwKn8A+SdgpCSUobnbMuxkrHAtoXui3vAw5svsjXfgrpKRrR9uRsT6goAPdzcNkhFrnm+kTokiM3FKCVGu0LcMTLQgsIVuu8izs4miH87SUNORR9SV6PlvYZig56WAy5RBvPkyckwoXU9NJ6Ep4Q4DPpiGlNNTdd3LUHfTDoQdCX9eekuy4+XyDshPQTldhKyBKS9ROubcOtbTu0wIgOoTNA7FXJG+1zoFa3SEkM7kH7OaXn7ElDkt+9droHFWepa+7d0FPrt8dfDtLqe7RaPPajNM4PLx35WqR4D0OSrctW5tAl5fawC52qZdcEe71yTbAxtZfP77hnaKQAD3HUj7ooHdjCJcdIlUHx2sGYQLag/vYdvUB2gPebfZyVc4AtVfV46seuiGFI7C2a5HqLkVbpjNOGwhBtDEDL2UrKcyznRf64eqfTE5ZrYsBi+MrWMzir6ASQ/HXI3iF+aer/TZRGlifzSMRR4EdloWmFNlC5oLZQv0bwrvrVgmzFg1LE8YLdcYTQ9MTbXcH6cNV0PmmEpuwRTWC2pDW2Qux+d5K9M44fioxewKgsHgcyu89WUJvWUWq7Cw==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secrets
      namespace: paperless

