---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-data
  namespace: mealie
  labels:
    app: mealie
    app.kubernetes.io/name: mealie-data
    app.kubernetes.io/instance: mealie
    app.kubernetes.io/component: data-storage
    app.kubernetes.io/part-of: mealie
spec:
  storageClassName: hcloud-volumes
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
