apiVersion: v1
kind: Service
metadata:
  name: mealie
  namespace: mealie
  labels:
    app: mealie
    app.kubernetes.io/name: mealie
    app.kubernetes.io/instance: mealie
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: web
      name: mealie-web
  selector:
    app: mealie

---
