apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ghost
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 19.5.10
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: ghost
  targetNamespace: ghost
  upgrade:
    crds: CreateReplace
  values:
    auth:
      enabled: false
    replica:
      replicaCount: 1
    volumePermissions:
      enabled: true
