apiVersion: v1
kind: Namespace
metadata:
  name: ghost
  labels:
    app.kubernetes.io/name: ghost
    app.kubernetes.io/instance: ghost
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: ghost
    app.kubernetes.io/version: "5.8"
