apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-pv
  namespace: ghost
  labels:
    app.kubernetes.io/name: ghost
    app.kubernetes.io/component: ghost-pv
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/rookian/k8s-volumes/ghost"
