apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-content
  namespace: ghost
  labels:
    app: ghost
    app.kubernetes.io/name: ghost
    app.kubernetes.io/instance: ghost
    app.kubernetes.io/version: "5.8"
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: ghost
spec:
  storageClassName: manual-ghost-content
  hostPath:
    path: "/home/rookian/k8s-volumes/ghost/content"
  accessModes:
  - ReadWriteMany 
  resources:
    requests:
    storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-ghost-pvc
  namespace: ghost
  labels:
    app: mysql-ghost
    app.kubernetes.io/name: mysql-ghost-pvc
    app.kubernetes.io/instance: ghost
    app.kubernetes.io/version: "5.8"
    app.kubernetes.io/component: database-storage
    app.kubernetes.io/part-of: ghost
spec:
  storageClassName: manual-ghost-mysql
  hostPath:
    path: "/home/rookian/k8s-volumes/ghost/mysql"
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
