---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: flux-system
spec:
  chart:
    spec:
      chart: bitnami/postgresql
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 12.8.2
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: postgres
  targetNamespace: postgres
  upgrade:
    crds: CreateReplace
