apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2023-08-11T12:53:52Z"
  labels:
    kubernetes.io/metadata.name: postgres
  name: postgres
  resourceVersion: "2228200"
  uid: 03e3ad96-b9d7-4eab-a3be-d53214134ff4
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
