apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secrets
  namespace: postgres
spec:
  encryptedData:
    postgres-password: AgA8Fk0BSwJpH/B6CcVKFDUC2ZgQYVHCcjaAodIgxCXeFE0qlap/3w+oaq0tIVaz5ih0ofkuQCzHcQCPNAJVoPOxc7zfdwi0j0aAVQ/cv04ATbdFVFxe0wRvdj+Doh6a+VH/lf0WyjWr1D+GaVfXqH8zOfVBytvYAxmKacpVtDeY6lOGjDwnWnF58cscd+H2vErp6R9jSipvtZbcOQyKlLqjr418utUm15jj59z9SWTCsMoXc5vaH+G2pUDOzu0xe70pGI142FRLSzuDl4qNIWW+B3QJdBBWA+83VSWY+v+qke9NlzxlvYuxwom8TuIBG6fg1uptKuDFfKmsY/xmQjFdOPe9EKAglJFPOUlJh1OfQAqo5JTOU27Y9Dhtj57gfjlwpvsi9myVDHpUlalagGkeetN+f1Yb/k7kpg5RgAZmEze7G0IkHt8Z5GLjnXKx8G+kHdAiejDOe+0DvfAcQ+NtXpcNH/18ActQlieFOp/OctJaSBmTeN7ybqzPRcpRuzywnu5aL+kKW7aQu0nqW3QKFVxF2epq7+Tb4lBQ98rgAtKlyk5SjNGfCy+Y93tYUCNgCRgrXxbWlzZ0oMR3OAY6FEF53tyuvyqbPPlNM0qItwLv0Wrv47L2gGQxKgAK7cmHoF8im2ivTRGWWQ5OxmbpJbCQHb/Ox4oOg2zUDF960GKFlG2Qc2caxRV6cKYwYP8J/On7PxgQuLplotNQaO268lYTeJZeUXG8MnwRv60Wyf9m7GCNE6vEWkpyVc1biNhxAQa7ZrJDuelMf5jGlxIunA==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secrets
      namespace: postgres

