apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secrets
  namespace: postgres
spec:
  encryptedData:
    postgres-password: AgCmHVXx0cbraAKr+CrAhEYe2hQrDFvNPPyK5JkUenxyy3zy5JEkXwJXtoTaDKXxfr50o008p/owrbCUbQ2AZeq1KuSEOZYUBeSfyioHGTZFDZJbYU4CPFYYl4gHLTlyCFnI41D/FrFFWuWEXSGgNuVJkzx+dQt574P6CVTe6HekYal90QiQ8x9ZEAS/PC29WEsVfBoE1gV2eyAvVcfMPND7A0xEwhiL9jMBoMxyqT/T9TPHVp9Miek0lJD+A4UDVvNiABY+B/devVL9963emGjH79kCsSGKYudCjIXzhAMB1Fti2p/zrWRMLrHW/pszCPLAhgSs0ImJOx+i4S8ewMZYAueF3IeOXMtqPUpY5bktcm0k7WX6bH5SVKLES4GCAXWiF8/DV30G/n0kdo5ifOPkuZa9lpZErn+2lj6QHxuMa3i5BEuMe+HuB4rV8jIMJfyXLAgsM/XHwjp5hYeWPjiEbGWl/u/Wd8DpVETeiPGkos44/0l6kwAzZLpvu8mnqPdlokvWWOT3bGI61Nq6xkb4ejbKsVZ4BOBJcbWruTQeIxdNjKfTk9ceS8Lhb+TblzD7mt0hEExSr3I3iEt+jzOfXzWw/r+wm0JSJl4FCGmu6Cnb1yhxgnTUjU+zte9VeCSuYiPjNFeDSHzyAuebDoPrGwe8bjiYHttpj0eWcN1sHBAMl6SFBNtmwT12VLFkdIofsG6VysCA+mG7zijTbS1+EbBDg6TvVWj4yWaPwqVNmMCcjttD8xY3LNBoc+5uSeoOlb36hT/2EG281yN0WUsmYA==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secrets
      namespace: postgres

