---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: flux-system
spec:
  chart:
    spec:
      chart: redis
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 18.0.0
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: redis
  targetNamespace: flux-system
  upgrade:
    crds: CreateReplace
  values:
    volumePermissions:
      enabled: true
