apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-redis-master0
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: data-master0
    type: local
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/rookian/k8s-volumes/redis-master0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-redis-replicas0
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: data-replicas0
    type: local
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/rookian/k8s-volumes/redis-replicas0"
