kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    kubernetes.io/metadata.name: tandoor
  name: nginx-config
  namespace: tandoor
data:
  nginx-config: |-
    events {
      worker_connections 1024;
    }
    http {
      include mime.types;
      server {
        listen 80;
        server_name _;

        client_max_body_size 16M;

        # serve static files
        location /static/ {
          alias /static/;
        }
        # serve media files
        location /media/ {
          alias /media/;
        }
      }
    }
