---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  namespace: tandoor
  labels:
    app.kubernetes.io/name: tandoor
    app.kubernetes.io/component: local-pv
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/rookian/k8s-volumes/tandoor"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: tandoor
  labels:
    app.kubernetes.io/name: tandoor
    app.kubernetes.io/component: media-pvc
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
  namespace: tandoor
  labels:
    app.kubernetes.io/name: tandoor
    app.kubernetes.io/component: static-pvc
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
