---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-media
  namespace: tandoor
  labels:
    app.kubernetes.io/name: tandoor
    app.kubernetes.io/component: local-pv-media
    type: local
spec:
  storageClassName: local-storage-media
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/rookian/k8s-volumes/tandoor/media"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-static
  namespace: tandoor
  labels:
    app.kubernetes.io/name: tandoor
    app.kubernetes.io/component: local-pv-static
    type: local
spec:
  storageClassName: local-storage-static
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/rookian/k8s-volumes/tandoor/static"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: tandoor
  labels:
    app.kubernetes.io/name: tandoor
    app.kubernetes.io/component: media-pvc
spec:
  storageClassName: local-storage-media
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
  namespace: tandoor
  labels:
    app.kubernetes.io/name: tandoor
    app.kubernetes.io/component: static-pvc
spec:
  storageClassName: local-storage-static
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
