apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-books
  namespace: calibre
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: calibre
  hostPath:
    path: /home/rookian/k8s-volumes/calibre/books
