---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-config
  namespace: calibre
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: calibre
  hostPath:
    path: /home/rookian/k8s-volumes/calibre/config
